<a href="https://colab.research.google.com/github/Saroj-lab/DataAcquisition/blob/main/DataAcquisitionCasestudy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import pandas as pd
import os
import time
from datetime import datetime
import numpy as np

In [20]:
DATA_PATH1 = '/content/population.csv'
DATA_PATH2 = '/content/gdp.xlsx'
DATA_PATH3 = '/content/internet_users.json'
DATA_PATH4 = '/content/literacy_rate.xml'
OUT_DTR = 'Outputs'
INTERVAL_SECONDS = 20
MAX_RUNS = 1

In [25]:
def extract():
    population_data = pd.read_csv(DATA_PATH1)
    population_data_len = len(population_data)
    print(f'Extracted {population_data_len} rows')
    #return population_data
    gdp_data = pd.read_excel(DATA_PATH2)
    gdp_data_len = len(gdp_data)
    print("extracted", gdp_data_len,"rows")
    #return gdp_data
    internet_users = pd.read_json(DATA_PATH3)
    internet_users_len = len(internet_users)
    print("extracted", internet_users, "rows")
    literacy_rate = pd.read_xml(DATA_PATH4)
    literacy_rate_len = len(literacy_rate)
    print("extracted", literacy_rate, "rows")
    return population_data,gdp_data,internet_users,literacy_rate



def transform(population_data,gdp_data,internet_users,literacy_rate):
    print("the first five rows  of population data is:", population_data.head())
    print("the shape of population data is:", population_data.shape)
    print("the type of population data is:", population_data.info())
    print("the column names of gdp is:", gdp_data.info())
    print("dataframe of internet users", internet_users)
    print("the dataframe of all required fields", literacy_rate)

In [26]:
population_data,gdp_data,internet_users,literacy_rate = extract()
cleaned_data = transform(population_data,gdp_data,internet_users,literacy_rate)

Extracted 25 rows
extracted 25 rows
extracted            country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000 rows
extracted               name  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5 rows
the first five rows  of population data is:          country  population
0  United States   331002651
1          China  1411778724
2          India  1380004385
3          Japan   125836021
4        Germany    83240525
the shape of population data is: (25, 2)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   country     25 non-null     object
 1   population  25 non-null     int64
dtypes: int64(1), object(1)
memory usage: 532.0+ bytes
the type of population data is: None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  25 non-null     object
 1   GDP      25 non-null     int64
dtypes: int64(1), object(1)
memory usage: 532.0+ bytes
the column names of gdp is: None
dataframe of internet users            country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000
the dataframe of all required fields               name  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

In [32]:
def transform1(population_data, gdp_data, internet_users, literacy_rate):
    datasets = {
        "Population": population_data,
        "GDP": gdp_data,
        "Internet Users": internet_users,
        "Literacy Rate": literacy_rate
    }

    for name, df in datasets.items():
        print(f"=== Exploring {name} Dataset ===")
        print(f"● Rows & Columns: {df.shape[0]} rows, {df.shape[1]} columns")
        print(f"● Column Names:  {df.columns.tolist()}")
        print(f"● Missing Values:\n{df.isnull().sum().to_string()}")
        print(f"● Duplicate Rows: {df.duplicated().sum()}")
        print("-" * 40)

    return population_data, gdp_data, internet_users, literacy_rate
_ = transform1(population_data, gdp_data, internet_users, literacy_rate)

=== Exploring Population Dataset ===
● Rows & Columns: 25 rows, 2 columns
● Column Names:  ['country', 'population']
● Missing Values:
country       0
population    0
● Duplicate Rows: 0
----------------------------------------
=== Exploring GDP Dataset ===
● Rows & Columns: 25 rows, 2 columns
● Column Names:  ['Country', 'GDP']
● Missing Values:
Country    0
GDP        0
● Duplicate Rows: 0
----------------------------------------
=== Exploring Internet Users Dataset ===
● Rows & Columns: 25 rows, 2 columns
● Column Names:  ['country', 'internet_users']
● Missing Values:
country           0
internet_users    0
● Duplicate Rows: 0
----------------------------------------
=== Exploring Literacy Rate Dataset ===
● Rows & Columns: 25 rows, 2 columns
● Column Names:  ['name', 'literacy_rate']
● Missing Values:
name             0
literacy_rate    0
● Duplicate Rows: 0
----------------------------------------

In [38]:
gdp_data = gdp_data.rename(columns={'Country': 'country'})


literacy_rate = literacy_rate.rename(columns={'name': 'country'})

print("Updated Column Names:")
print("GDP:", gdp_data.columns.tolist())
print("Literacy Rate:", literacy_rate.columns.tolist())

Updated Column Names:
GDP: ['country', 'GDP']
Literacy Rate: ['country', 'literacy_rate']

In [37]:

population_data['population'] = pd.to_numeric(population_data['population'], errors='coerce')
gdp_data['GDP'] = pd.to_numeric(gdp_data['GDP'], errors='coerce')
internet_users['internet_users'] = pd.to_numeric(internet_users['internet_users'], errors='coerce')
literacy_rate['literacy_rate'] = pd.to_numeric(literacy_rate['literacy_rate'], errors='coerce')

print("Data types successfully validated and converted!")

Data types successfully validated and converted!

In [36]:

merged_df = pd.merge(population_data, gdp_data, on='country', how='inner')

merged_df = pd.merge(merged_df, internet_users, on='country', how='inner')

final_df = pd.merge(merged_df, literacy_rate, on='country', how='inner')


print(f"Successfully merged! Final DataFrame Shape: {final_df.shape}")
display(final_df.head())

Successfully merged! Final DataFrame Shape: (25, 5)

         country  population       GDP  internet_users  literacy_rate
0  United States   331002651  30500000       312000000           99.0
1          China  1411778724  19230000      1080000000           97.2
2          India  1380004385   4187000       850000000           77.7
3          Japan   125836021   4180000       118000000           99.0
4        Germany    83240525   4744000        79000000           99.0

In [39]:
final_df['Internet Penetration (%)'] = round((final_df['internet_users'] / final_df['population']) * 100, 2)

final_df['GDP Per Capita'] = round(final_df['GDP'] / final_df['population'], 2)

print("Calculated columns added successfully!")
display(final_df[['country', 'population', 'internet_users', 'Internet Penetration (%)', 'GDP', 'GDP Per Capita']].head())

Calculated columns added successfully!

,country,population,internet_users,Internet Penetration (%),GDP,GDP Per Capita
0,United States,331002651,312000000,94.26,30500000,0.09
1,China,1411778724,1080000000,76.50,19230000,0.01
2,India,1380004385,850000000,61.59,4187000,0.00
3,Japan,125836021,118000000,93.77,4180000,0.03
4,Germany,83240525,79000000,94.91,4744000,0.06

In [40]:
import sqlite3

conn = sqlite3.connect('etl_database.db')

final_df.to_sql('Country_statistics', conn, if_exists='replace', index=False)

print("Database created and 'Country_statistics' table successfully populated!")

query = "SELECT * FROM Country_statistics LIMIT 5;"
verified_df = pd.read_sql(query, conn)

print("\nVerification - Reading back first 5 rows directly from SQLite:")
display(verified_df)

Database created and 'Country_statistics' table successfully populated!

Verification - Reading back first 5 rows directly from SQLite:

,country,population,GDP,internet_users,literacy_rate,Internet Penetration (%),GDP Per Capita
0,United States,331002651,30500000,312000000,99.0,94.26,0.09
1,China,1411778724,19230000,1080000000,97.2,76.50,0.01
2,India,1380004385,4187000,850000000,77.7,61.59,0.00
3,Japan,125836021,4180000,118000000,99.0,93.77,0.03
4,Germany,83240525,4744000,79000000,99.0,94.91,0.06

In [41]:
import pandas as pd
import sqlite3
conn = sqlite3.connect('etl_database.db')

query = "SELECT * FROM Country_statistics;"
verified_df = pd.read_sql(query, conn)

print("=== Database Verification Summary ===")
print(f"● Table Name:          Country_statistics")
print(f"● Verified Row Count:  {len(verified_df)} rows")
print(f"● Verified Column Count: {verified_df.shape[1]} columns")
print(f"● Database Columns:    {verified_df.columns.tolist()}")
print("-" * 37)

print("\nPreview of data loaded inside SQLite:")
display(verified_df.head())

conn.close()

=== Database Verification Summary ===
● Table Name:          Country_statistics
● Verified Row Count:  25 rows
● Verified Column Count: 7 columns
● Database Columns:    ['country', 'population', 'GDP', 'internet_users', 'literacy_rate', 'Internet Penetration (%)', 'GDP Per Capita']
-------------------------------------

Preview of data loaded inside SQLite:

,country,population,GDP,internet_users,literacy_rate,Internet Penetration (%),GDP Per Capita
0,United States,331002651,30500000,312000000,99.0,94.26,0.09
1,China,1411778724,19230000,1080000000,97.2,76.50,0.01
2,India,1380004385,4187000,850000000,77.7,61.59,0.00
3,Japan,125836021,4180000,118000000,99.0,93.77,0.03
4,Germany,83240525,4744000,79000000,99.0,94.91,0.06

In [50]:

print("--- 1. Top 5 Countries by GDP ---")
print(final_df.nlargest(5, 'GDP')[['country', 'GDP']])
print("\n" + "="*40 + "\n")

print("--- 2. Top 5 Countries by Population ---")
print(final_df.nlargest(5, 'population')[['country', 'population']])
print("\n" + "="*40 + "\n")

print("--- 3. Average Literacy Rate ---")
print(f"{final_df['literacy_rate'].mean():.2f}%")
print("\n" + "="*40 + "\n")

print("--- 4. Countries with Literacy Rate > 90% ---")
print(final_df[final_df['literacy_rate'] > 90][['country', 'literacy_rate']])
print("\n" + "="*40 + "\n")

print("--- 5. Countries with Internet Penetration > 70% ---")
print(final_df[final_df['Internet Penetration (%)'] > 70][['country', 'Internet Penetration (%)']])
print("\n" + "="*40 + "\n")

print("--- 6. Top 5 Countries by GDP Per Capita ---")
print(final_df.nlargest(5, 'GDP Per Capita')[['country', 'GDP Per Capita']])
print("\n" + "="*40 + "\n")

print("--- 7. Total Population ---")
print(f"{final_df['population'].sum():,}")
print("\n" + "="*40 + "\n")

print("--- 8. Average Internet Penetration ---")
print(f"{final_df['Internet Penetration (%)'].mean():.2f}%")
print("\n" + "="*40 + "\n")

print("--- 9. Country with Highest Internet Users ---")
print(final_df.nlargest(1, 'internet_users')[['country', 'internet_users']])
print("\n" + "="*40 + "\n")

print("--- 10. Correlation between Literacy Rate and Internet Penetration ---")
correlation = final_df['literacy_rate'].corr(final_df['Internet Penetration (%)'])
print(f"Correlation coefficient: {correlation:.4f}")

--- 1. Top 5 Countries by GDP ---
         country       GDP
0  United States  30500000
1          China  19230000
4        Germany   4744000
2          India   4187000
3          Japan   4180000

========================================

--- 2. Top 5 Countries by Population ---
          country  population
1           China  1411778724
2           India  1380004385
0   United States   331002651
15      Indonesia   273523615
10         Brazil   212559417

========================================

--- 3. Average Literacy Rate ---
97.25%

========================================

--- 4. Countries with Literacy Rate > 90% ---
           country  literacy_rate
0    United States           99.0
1            China           97.2
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

========================================

--- 5. Countries with Internet Penetration > 70% ---
           country  Internet Penetration (%)
0    United States                     94.26
1            China                     76.50
3            Japan                     93.77
4          Germany                     94.91
5   United Kingdom                     97.22
6           France                     94.98
7            Italy                     92.62
8           Canada                     94.72
9        Australia                     93.43
10          Brazil                     85.15
11          Russia                     85.65
12     South Korea                     96.56
13           Spain                     94.11
14          Mexico                     79.11
15       Indonesia                     77.51
16    Saudi Arabia                     97.66
17          Turkey                     81.81
18    South Africa                     72.50
19       Argentina                     90.72
20     Netherlands                     97.47
21     Switzerland                     98.21
22          Sweden                     97.55
23          Norway                     97.76
24       Singapore                     95.72

========================================

--- 6. Top 5 Countries by GDP Per Capita ---
          country  GDP Per Capita
21    Switzerland            0.11
23         Norway            0.11
0   United States            0.09
24      Singapore            0.09
9       Australia            0.07

========================================

--- 7. Total Population ---
4,720,039,725

========================================

--- 8. Average Internet Penetration ---
89.66%

========================================

--- 9. Country with Highest Internet Users ---
  country  internet_users
1   China      1080000000

========================================

--- 10. Correlation between Literacy Rate and Internet Penetration ---
Correlation coefficient: 0.7728

In [51]:

conn = sqlite3.connect('etl_database.db')

print("--- 11. Top 5 Countries by GDP ---")
query_11 = "SELECT country, GDP FROM Country_statistics ORDER BY GDP DESC LIMIT 5;"
print(pd.read_sql(query_11, conn))
print("\n" + "="*50 + "\n")

print("--- 12. Average Literacy Rate ---")
query_12 = "SELECT AVG(literacy_rate) AS Average_Literacy_Rate FROM Country_statistics;"
print(pd.read_sql(query_12, conn))
print("\n" + "="*50 + "\n")

print("--- 13. Countries with Literacy Rate Above 90% ---")
query_13 = "SELECT country, literacy_rate FROM Country_statistics WHERE literacy_rate > 90;"
print(pd.read_sql(query_13, conn))
print("\n" + "="*50 + "\n")

print("--- 14. Top 5 Countries with Highest Internet Penetration ---")
query_14 = "SELECT country, `Internet Penetration (%)` FROM Country_statistics ORDER BY `Internet Penetration (%)` DESC LIMIT 5;"
print(pd.read_sql(query_14, conn))
print("\n" + "="*50 + "\n")

print("--- 15. Total Population ---")
query_15 = "SELECT SUM(population) AS Total_Population FROM Country_statistics;"
print(pd.read_sql(query_15, conn))
print("\n" + "="*50 + "\n")

print("--- 16. Country with the Highest GDP Per Capita ---")
query_16 = "SELECT country, `GDP Per Capita` FROM Country_statistics ORDER BY `GDP Per Capita` DESC LIMIT 1;"
print(pd.read_sql(query_16, conn))
print("\n" + "="*50 + "\n")

print("--- 17. Exporting Dataset to CSV ---")
final_df.to_csv('final_merged_countries.csv', index=False)
print("File successfully saved as 'final_merged_countries.csv'!")
print("\n" + "="*50 + "\n")

print("--- 18. Top 10 Countries by GDP Per Capita (Descending) ---")
query_18 = "SELECT country, `GDP Per Capita`, GDP, population FROM Country_statistics ORDER BY `GDP Per Capita` DESC LIMIT 10;"
print(pd.read_sql(query_18, conn))

conn.close()

--- 11. Top 5 Countries by GDP ---
         country       GDP
0  United States  30500000
1          China  19230000
2        Germany   4744000
3          India   4187000
4          Japan   4180000

==================================================

--- 12. Average Literacy Rate ---
   Average_Literacy_Rate
0                 97.248

==================================================

--- 13. Countries with Literacy Rate Above 90% ---
           country  literacy_rate
0    United States           99.0
1            China           97.2
2            Japan           99.0
3          Germany           99.0
4   United Kingdom           99.0
5           France           99.0
6            Italy           99.0
7           Canada           99.0
8        Australia           99.0
9           Brazil           93.2
10          Russia           99.7
11     South Korea           98.8
12           Spain           98.6
13          Mexico           95.4
14       Indonesia           96.0
15    Saudi Arabia           97.3
16          Turkey           96.7
17    South Africa           95.0
18       Argentina           99.1
19     Netherlands           99.0
20     Switzerland           99.0
21          Sweden           99.0
22          Norway          100.0
23       Singapore           97.5

==================================================

--- 14. Top 5 Countries with Highest Internet Penetration ---
        country  Internet Penetration (%)
0   Switzerland                     98.21
1        Norway                     97.76
2  Saudi Arabia                     97.66
3        Sweden                     97.55
4   Netherlands                     97.47

==================================================

--- 15. Total Population ---
   Total_Population
0        4720039725

==================================================

--- 16. Country with the Highest GDP Per Capita ---
       country  GDP Per Capita
0  Switzerland            0.11

==================================================

--- 17. Exporting Dataset to CSV ---
File successfully saved as 'final_merged_countries.csv'!

==================================================

--- 18. Top 10 Countries by GDP Per Capita (Descending) ---
          country  GDP Per Capita       GDP  population
0     Switzerland            0.11    940000     8654622
1          Norway            0.11    580000     5421241
2   United States            0.09  30500000   331002651
3       Singapore            0.09    530000     5850342
4       Australia            0.07   1880000    25687041
5     Netherlands            0.07   1150000    17441139
6         Germany            0.06   4744000    83240525
7  United Kingdom            0.06   3839000    67886011
8          Canada            0.06   2250000    38005238
9          Sweden            0.06    650000    10353442